CREATE TABLE TBL_SIMULATION (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  simulator_name VARCHAR(255) NOT NULL,
  parameter_string TEXT NULL,
  output_file TEXT NULL,
  updated_at TIMESTAMP NOT NULL,
  PRIMARY KEY(id)
)
TYPE=InnoDB;

CREATE TABLE TBL_RESULT (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  simulation_id INTEGER UNSIGNED NOT NULL,
  name VARCHAR(255) NULL,
  value DOUBLE NULL,
  updated_at TIMESTAMP NOT NULL,
  PRIMARY KEY(id),
  INDEX TBL_RESULT_FKIndex1(simulation_id),
  FOREIGN KEY(simulation_id)
    REFERENCES TBL_SIMULATION(id)
      ON DELETE CASCADE
      ON UPDATE CASCADE
)
TYPE=InnoDB;

